# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: saolivei <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/03/26 17:02:18 by saolivei          #+#    #+#              #
#    Updated: 2018/03/26 17:02:24 by saolivei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRCS = main.c

OUT = ft_display_file.o

all:
	gcc -Wall -Wextra -Werror $(SRCS) -o $(NAME)

clean:
	rm -f $(OUT)

fclean: clean
	rm -f $(NAME)